allow-exact-repetitions = true
check-private-items = true
enforce-iter-loop-reborrow = true
enum-variant-name-threshold = 1
excessive-nesting-threshold = 5
lint-commented-code = true
matches-for-let-else = "AllTypes"
max-fn-params-bools = 2
max-struct-bools = 3
max-suggested-slice-pattern-length = 3
max-trait-bounds = 1
module-items-ordered-within-groupings = "none"
single-char-binding-names-threshold = 4
source-item-ordering = []
struct-field-name-threshold = 1
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
upper-case-acronyms-aggressive = true
