allow = [
  # Opposites of checked lints, covered by other lints.
  "non_ascii_idents",
  "clippy::allow_attributes",
  "clippy::self_named_module_files",
  "clippy::semicolon_inside_block",
  "clippy::separated_literal_suffix",
  "clippy::shadow_reuse",
  # Core language features and proper use of common APIs.
  "ambiguous_negative_literals",
  "closure_returning_async_block",
  "elided_lifetimes_in_paths",
  "if_let_rescope",
  "rust_2021_incompatible_closure_captures",
  "tail_expr_drop_order",
  "unsafe_code",
  "unstable_features",
  "clippy::arithmetic_side_effects",
  "clippy::as_conversions",
  "clippy::as_underscore",
  "clippy::big_endian_bytes",
  "clippy::cast_possible_truncation",
  "clippy::cast_possible_wrap",
  "clippy::cast_precision_loss",
  "clippy::cast_sign_loss",
  "clippy::copy_iterator",
  "clippy::create_dir",
  "clippy::default_numeric_fallback",
  "clippy::else_if_without_else",
  "clippy::exhaustive_enums",
  "clippy::exhaustive_structs",
  "clippy::expect_used",
  "clippy::field_scoped_visibility_modifiers",
  "clippy::float_arithmetic",
  "clippy::float_cmp",
  "clippy::float_cmp_const",
  "clippy::fn_to_numeric_cast_any",
  "clippy::host_endian_bytes",
  "clippy::impl_trait_in_params",
  "clippy::implicit_return",
  "clippy::indexing_slicing",
  "clippy::inline_always",
  "clippy::inline_asm_x86_att_syntax",
  "clippy::inline_asm_x86_intel_syntax",
  "clippy::integer_division",
  "clippy::integer_division_remainder_used",
  "clippy::iter_over_hash_type",
  "clippy::let_underscore_untyped",
  "clippy::linkedlist",
  "clippy::little_endian_bytes",
  "clippy::min_ident_chars",
  "clippy::missing_assert_message",
  "clippy::missing_trait_methods",
  "clippy::modulo_arithmetic",
  "clippy::needless_for_each",
  "clippy::non_ascii_literal",
  "clippy::panic",
  "clippy::panic_in_result_fn",
  "clippy::partial_pub_fields",
  "clippy::pattern_type_mismatch",
  "clippy::pointer_format",
  "clippy::precedence",
  "clippy::precedence_bits",
  "clippy::print_stderr",
  "clippy::print_stdout",
  "clippy::pub_use",
  "clippy::pub_without_shorthand",
  "clippy::question_mark_used",
  "clippy::ref_binding_to_reference",
  "clippy::ref_patterns",
  "clippy::rest_pat_in_fully_bound_structs",
  "clippy::similar_names",
  "clippy::single_call_fn",
  "clippy::single_char_lifetime_names",
  "clippy::std_instead_of_alloc",
  "clippy::std_instead_of_core",
  "clippy::string_add",
  "clippy::string_add_assign",
  "clippy::todo",
  "clippy::unchecked_time_subtraction",
  "clippy::unimplemented",
  "clippy::unreachable",
  "clippy::unwrap_in_result",
  "clippy::unwrap_used",
  # While this is bad, it's common in real code and promoting it to a warning would bloat diagnosis.
  "clippy::multiple_crate_versions",
  # Poorly implemented.
  "clippy::cognitive_complexity",
  # Many false positives.
  "missing_copy_implementations",
  "clippy::decimal_literal_representation",
]
warn = [
  # Code style, refactor artifacts, simplification, performance, likely mistakes. Should not be allowed.
  "absolute_paths_not_starting_with_crate",
  "explicit_outlives_requirements",
  "macro_use_extern_crate",
  "redundant_imports",
  "redundant_lifetimes",
  "single_use_lifetimes",
  "trivial_casts",
  "trivial_numeric_casts",
  "unit_bindings",
  "unreachable_pub",
  "unused_crate_dependencies",
  "unused_extern_crates",
  "unused_import_braces",
  "unused_lifetimes",
  "unused_macro_rules",
  "unused_qualifications",
  "clippy::absolute_paths",
  "clippy::alloc_instead_of_core",
  "clippy::arbitrary_source_item_ordering",
  "clippy::assertions_on_result_states",
  "clippy::assigning_clones",
  "clippy::bool_to_int_with_if",
  "clippy::branches_sharing_code",
  "clippy::case_sensitive_file_extension_comparisons",
  "clippy::cast_lossless",
  "clippy::checked_conversions",
  "clippy::clear_with_drain",
  "clippy::cloned_instead_of_copied",
  "clippy::collection_is_never_read",
  "clippy::comparison_chain",
  "clippy::default_trait_access",
  "clippy::deref_by_slicing",
  "clippy::elidable_lifetime_names",
  "clippy::empty_enums",
  "clippy::empty_enum_variants_with_brackets",
  "clippy::empty_structs_with_brackets",
  "clippy::equatable_if_let",
  "clippy::error_impl_error",
  "clippy::expl_impl_clone_on_copy",
  "clippy::explicit_deref_methods",
  "clippy::explicit_into_iter_loop",
  "clippy::explicit_iter_loop",
  "clippy::filter_map_next",
  "clippy::flat_map_option",
  "clippy::from_iter_instead_of_collect",
  "clippy::if_then_some_else_none",
  "clippy::ignored_unit_patterns",
  "clippy::implicit_clone",
  "clippy::imprecise_flops",
  "clippy::inconsistent_struct_constructor",
  "clippy::index_refutable_slice",
  "clippy::inefficient_to_string",
  "clippy::invalid_upcast_comparisons",
  "clippy::ip_constant",
  "clippy::items_after_statements",
  "clippy::iter_filter_is_ok",
  "clippy::iter_filter_is_some",
  "clippy::iter_not_returning_iterator",
  "clippy::iter_on_empty_collections",
  "clippy::iter_on_single_items",
  "clippy::iter_with_drain",
  "clippy::large_digit_groups",
  "clippy::macro_use_imports",
  "clippy::manual_assert",
  "clippy::manual_instant_elapsed",
  "clippy::manual_is_power_of_two",
  "clippy::manual_is_variant_and",
  "clippy::manual_let_else",
  "clippy::manual_midpoint",
  "clippy::manual_string_new",
  "clippy::many_single_char_names",
  "clippy::map_unwrap_or",
  "clippy::map_with_unused_argument_over_ranges",
  "clippy::match_bool",
  "clippy::match_same_arms",
  "clippy::mismatching_type_param_order",
  "clippy::missing_asserts_for_indexing",
  "clippy::mod_module_files",
  "clippy::module_name_repetitions",
  "clippy::multiple_inherent_impl",
  "clippy::naive_bytecount",
  "clippy::needless_bitwise_bool",
  "clippy::needless_collect",
  "clippy::needless_continue",
  "clippy::needless_pass_by_ref_mut",
  "clippy::needless_pass_by_value",
  "clippy::needless_raw_string_hashes",
  "clippy::needless_raw_strings",
  "clippy::negative_feature_names",
  "clippy::no_effect_underscore_binding",
  "clippy::non_std_lazy_statics",
  "clippy::nonstandard_macro_braces",
  "clippy::option_as_ref_cloned",
  "clippy::option_if_let_else",
  "clippy::pub_underscore_fields",
  "clippy::pub_with_shorthand",
  "clippy::rc_mutex",
  "clippy::redundant_clone",
  "clippy::redundant_closure_for_method_calls",
  "clippy::redundant_else",
  "clippy::redundant_feature_names",
  "clippy::redundant_pub_crate",
  "clippy::redundant_test_prefix",
  "clippy::redundant_type_annotations",
  "clippy::return_and_then",
  "clippy::self_only_used_in_recursion",
  "clippy::semicolon_if_nothing_returned",
  "clippy::semicolon_outside_block",
  "clippy::shadow_same",
  "clippy::shadow_unrelated",
  "clippy::single_char_pattern",
  "clippy::single_match_else",
  "clippy::single_option_map",
  "clippy::str_to_string",
  "clippy::string_lit_chars_any",
  "clippy::struct_field_names",
  "clippy::suboptimal_flops",
  "tail_expr_drop_order",
  "clippy::trait_duplication_in_bounds",
  "clippy::try_err",
  "clippy::tuple_array_conversions",
  "clippy::type_repetition_in_bounds",
  "clippy::uninhabited_references",
  "clippy::uninlined_format_args",
  "clippy::unnecessary_join",
  "clippy::unnecessary_literal_bound",
  "clippy::unnecessary_safety_comment",
  "clippy::unnecessary_safety_doc",
  "clippy::unnecessary_semicolon",
  "clippy::unnecessary_struct_initialization",
  "clippy::unnecessary_wraps",
  "clippy::unneeded_field_pattern",
  "clippy::unnested_or_patterns",
  "clippy::unreadable_literal",
  "clippy::unseparated_literal_suffix",
  "clippy::unseparated_literal_suffix",
  "clippy::unused_async",
  "clippy::unused_peekable",
  "clippy::unused_result_ok",
  "clippy::unused_rounding",
  "clippy::unused_self",
  "clippy::unused_trait_names",
  "clippy::use_self",
  "clippy::used_underscore_binding",
  "clippy::used_underscore_items",
  "clippy::useless_let_if_seq",
  "clippy::verbose_bit_mask",
  "clippy::verbose_file_reads",
  "clippy::zero_sized_map_values",
  # Documentation, debug remnants, tests, error messages. Should only be allowed during development.
  "missing_docs",
  "clippy::allow_attributes_without_reason",
  "clippy::cargo_common_metadata",
  "clippy::dbg_macro",
  "clippy::doc_broken_link",
  "clippy::doc_comment_double_space_linebreaks",
  "clippy::doc_include_without_cfg",
  "clippy::doc_link_code",
  "clippy::doc_link_with_quotes",
  "clippy::doc_markdown",
  "clippy::ignore_without_reason",
  "clippy::missing_docs_in_private_items",
  "clippy::missing_errors_doc",
  "clippy::missing_fields_in_debug",
  "clippy::missing_panics_doc",
  "clippy::multiple_unsafe_ops_per_block",
  "clippy::should_panic_without_expect",
  "clippy::tests_outside_test_module",
  "clippy::too_long_first_doc_paragraph",
  "clippy::undocumented_unsafe_blocks",
  "clippy::use_debug",
  # Suspicious or dangerous patterns, possibly with legitimate use cases. May need to be allowed.
  "deref_into_dyn_supertrait",
  "ffi_unwind_calls",
  "impl_trait_overcaptures",
  "impl_trait_redundant_captures",
  "let_underscore_drop",
  "meta_variable_misuse",
  "missing_debug_implementations",
  "unnameable_types",
  "unsafe_op_in_unsafe_fn",
  "unused_results",
  "variant_size_differences",
  "clippy::clone_on_ref_ptr",
  "clippy::coerce_container_to_any",
  "clippy::default_union_representation",
  "clippy::derive_partial_eq_without_eq",
  "clippy::empty_drop",
  "clippy::fallible_impl_from",
  "clippy::filetype_is_file",
  "clippy::fn_params_excessive_bools",
  "clippy::format_collect",
  "clippy::format_push_string",
  "clippy::future_not_send",
  "clippy::get_unwrap",
  "clippy::large_include_file",
  "clippy::large_types_passed_by_value",
  "clippy::let_underscore_must_use",
  "clippy::literal_string_with_formatting_args",
  "clippy::lossy_float_literal",
  "clippy::map_err_ignore",
  "clippy::match_wild_err_arm",
  "clippy::match_wildcard_for_single_variants",
  "clippy::maybe_infinite_iter",
  "clippy::mem_forget",
  "clippy::mixed_read_write_in_expression",
  "clippy::option_option",
  "clippy::or_fun_call",
  "clippy::path_buf_push_overwrite",
  "clippy::pathbuf_init_then_push",
  "clippy::range_minus_one",
  "clippy::range_plus_one",
  "clippy::rc_buffer",
  "clippy::read_zero_byte_vec",
  "clippy::renamed_function_params",
  "clippy::return_self_not_must_use",
  "clippy::same_functions_in_if_condition",
  "clippy::same_name_method",
  "clippy::set_contains_or_insert",
  "clippy::significant_drop_in_scrutinee",
  "clippy::significant_drop_tightening",
  "clippy::str_split_at_newline",
  "clippy::string_slice",
  "clippy::struct_excessive_bools",
  "clippy::suspicious_operation_groupings",
  "clippy::suspicious_xor_used_as_pow",
  "clippy::trailing_empty_array",
  "clippy::unchecked_time_subtraction",
  "clippy::unicode_not_nfc",
  "clippy::unnecessary_box_returns",
  "clippy::unnecessary_debug_formatting",
  "clippy::unnecessary_self_imports",
  "clippy::unsafe_derive_deserialize",
  "clippy::volatile_composites",
  "clippy::while_float",
  # Suggestions. May need to be allowed frequently.
  "clippy::if_not_else",
  "clippy::into_iter_without_iter",
  "clippy::iter_without_into_iter",
  "clippy::missing_const_for_fn",
  "clippy::missing_inline_in_public_items",
  "clippy::must_use_candidate",
  "clippy::mutex_atomic",
  "clippy::mutex_integer",
  "clippy::non_zero_suggestions",
  "clippy::stable_sort_primitive",
  "clippy::string_lit_as_bytes",
  "clippy::too_many_lines",
  "clippy::trivial_regex",
  "clippy::wildcard_enum_match_arm",
  # Platform/target_dependent, arbitrary stack size limits.
  "linker_messages",
  "clippy::large_futures",
  "clippy::large_stack_arrays",
  "clippy::large_stack_frames",
  "clippy::trivially_copy_pass_by_ref",
]
deny = [
  # Promoted from warnings: certain mistakes.
  "deprecated_safe_2024",
  "clippy::cast_enum_truncation",
  "clippy::cast_nan_to_int",
  "clippy::duplicated_attributes",
  "clippy::fn_to_numeric_cast",
  "clippy::forget_non_drop",
  "clippy::four_forward_slashes",
  "clippy::from_raw_with_void_ptr",
  "clippy::incompatible_msrv",
  "clippy::non_canonical_clone_impl",
  "clippy::non_canonical_partial_ord_impl",
  "clippy::pointers_in_nomem_asm_block",
  # Bad ideas.
  "clippy::as_ptr_cast_mut",
  "clippy::cfg_not_test",
  "clippy::debug_assert_with_mut_call",
  "clippy::disallowed_script_idents",
  "clippy::empty_loop",
  "clippy::enum_glob_use",
  "clippy::exit",
  "clippy::implicit_hasher",
  "clippy::infinite_loop",
  "clippy::missing_spin_loop",
  "clippy::mut_mut",
  "clippy::non_send_fields_in_send_ty",
  "clippy::ref_option",
  "clippy::ref_option_ref",
  "clippy::wildcard_dependencies",
  "clippy::wildcard_imports",
  # Unsafe patterns with safe(r) alternatives, unsafe code parading as safe.
  "missing_unsafe_on_extern",
  "unsafe_attr_outside_unsafe",
  "clippy::as_pointer_underscore",
  "clippy::borrow_as_ptr",
  "clippy::cast_ptr_alignment",
  "clippy::cast_slice_from_raw_parts",
  "clippy::crosspointer_transmute",
  "clippy::manual_dangling_ptr",
  "clippy::no_mangle_with_rust_abi",
  "clippy::ptr_as_ptr",
  "clippy::ptr_cast_constness",
  "clippy::ref_as_ptr",
  "clippy::swap_ptr_to_ref",
  "clippy::transmute_ptr_to_ptr",
  "clippy::transmute_undefined_repr",
  # Forward compatibility for older Rust versions.
  "keyword_idents_2018",
  "keyword_idents_2024",
  "rust_2021_incompatible_or_patterns",
  "rust_2021_prefixes_incompatible_syntax",
  "rust_2021_prelude_collisions",
  "rust_2024_guarded_string_incompatible_syntax",
  "rust_2024_incompatible_pat",
  "rust_2024_prelude_collisions",
]
